def test_package_imports() -> None:
    import hybridmodels

    expected = {
        "BoundedPredictor",
        "BoundScaler",
        "BucketPayload",
        "ChannelObs",
        "CovariateSelector",
        "Dataset",
        "EvosaxTrainingConfig",
        "EvosaxUI",
        "Experiment",
        "KANPredictor",
        "LOSS_REGISTRY",
        "MLPPredictor",
        "OptaxTrainingConfig",
        "Predictor",
        "RichEvosaxUI",
        "RichTrainingUI",
        "SOLVER_REGISTRY",
        "SilentUI",
        "SolverConfig",
        "TrainingUI",
        "bal_mle",
        "bal_mse",
        "default_trainable",
        "fold",
        "freeze_modules_of_type",
        "freeze_paths",
        "freeze_where",
        "load_predictors",
        "load_run",
        "make_dataset",
        "make_experiment",
        "masked_mle",
        "masked_mse",
        "predict_bucket",
        "predict_dataset",
        "register_solver",
        "reinitialize_pytree_with_key",
        "reinitialize_with_key",
        "save_predictors",
        "save_run",
        "split_dataset",
        "train_with_evosax",
        "train_with_optax",
        "trainable_mask",
    }
    assert set(hybridmodels.__all__) == expected
    for name in expected:
        getattr(hybridmodels, name)
